site:
  template: standard
  updated: true
  navBar:
    links:
      - title: Courses
        link: /#courses
      - title: Events
        link: /events
      - title: Blog
        link: /blog
  brand:
    logo: /static/1733490887414-logo.png
    description: Master the art of product building and turn your ideas into
      successful, scalable products
    ogImage: /icon/torqbit.png
    favicon: /favicon.ico
    socialLinks:
      discord: https://discord.gg/NserMXcx
      github: https://github.com/torqbit
      youtube: https://www.youtube.com/@torqbit
    name: source Academy
    brandColor: "#f7bd7a"
    title: Spreads peace and harmony
    icon: /static/1733490117864-icon.png
  darkMode: true
  heroSection:
    title: The Awesomest teaching platform
    description: >
      Torqbit, an open-source platform, serves as a learning management software
      that works for single person to largest educational institutions
    actionButtons:
      primary:
        label: Get Started
        link: /dashboad
      secondary:
        label: Contact Us
        link: mailto:support@torqbit.com
    banner:
      lightModePath: /static/1733494112613-lightModePath.png
      darkModePath: /static/1733494092015-darkModePath.png
      position: background
  sections:
    feature:
      featureInfo:
        featureList:
          - img: /static/1733491007377-feature-firsticon.png
            title: hjjjh
            description: jjgk
            link: /docs/auth
          - img: /static/1733490998141-feature-secondicon.png
            title: Authentication
            description: Configure authentication with Google, Github or any other auth
              provider supported by NextAuth
            link: /docs/auth
          - img: /static/1733494176234-feature-thirdicon.jpg
            title: Email
            description: Configure authentication
        title: Features
        description: Features for the learning platform
    courses:
      enable: false
      title: Courses list
      description: Courses description for alll
    blog:
      enable: true
      title: Blogs
      description: Description on blogs
